### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by ghost** [utilForever/game-developer-roadmap#1]
I've been collecting resources for game development for a little while. Thought I share my list collection to possibly help with the resources part of the TODO.

- [A Study Path for Game Programmer](https://github.com/miloyip/game-programmer)
- [Blizzard Software Engineering Reading (Associate)](https://www.amazon.com/gp/richpub/listmania/fullview/R2LC80THGVDJHI)
- [Blizzard Software Engineering Reading (Mid-level)](https://www.amazon.com/gp/richpub/listmania/fullview/R1C0VA4J8ZBURC)
- [Blizzard Software Engineering Reading (Senior)](https://www.amazon.com/gp/richpub/listmania/fullview/R2FZ98PSM92N7F/)
- [Books For Game Developers](http://mrelusive.com/books/books.html)
- [Useful programming and game development resources](https://eliasdaler.github.io/programming-and-gamedev-resources/)
- [Teach Yourself Computer Science](https://teachyourselfcs.com/)
- [The Definitive C++ Book Guide and List](http://stackoverflow.com/a/388282)

**Comment by nikitavoloboev** [comment]
I am making an [interactive mind map of all world's knowledge](https://github.com/nikitavoloboev/knowledge-map). 

I have a mind map for [game development](https://my.mindnode.com/rMqH25BBnT8N9Frhv3L6YCk8NozigyGWgjrgPmjE#38.2,-46.8,2) there too. If you want to improve it, you can. :)

**Comment by utilForever** [comment]
@rby90 @nikitavoloboev Thanks, I'll consider it. :)
