### ISSUE TITLE
Make it more readable 

### ISSUE THREAD

**Issue by GabrielCoelho** [utilForever/game-developer-roadmap#11]
I know that, in any programming path, we'll have a lot of important informations, such as a lot of necessary knowledge. But making *90% of the paths recommended or necessary itsn't cool*. 

- Try to split it out and reavaliate what is really important.  (as we can see in the Web Developer Roadmap inspiration repo, there's many important and recommended, but there's a plenty of possibilities and "pick any" ways.) 

- Sub-divide the client path into Graphics and Programming paths, to let the future Game Developer choose what is really usefull for him/her. 

- Give spaces to make it clear what is the begginer, intemediate and advanced steps. (Learn the basics, getting deeper, maximize your skills, respectively) 

In my first try to improve this repo, those are the most important to me, to make it clear for 2018 update and later on 2019!

**Comment by utilForever** [comment]
I'll consider your suggestion while I update this repo. Thanks. :tada:
