### ISSUE TITLE
Add Game Producer / Marketing Guy

### ISSUE THREAD

**Issue by dkotama** [utilForever/game-developer-roadmap#12]
Hi thank you for curated all the insight it really helpful,

To market a game or Producing it to final product i think management skill about scaling the game size or choose it market segment is super important. And game producer or game PR guy were still in many needs by small to big studios. If we can add this to the insight i think it will be helpful to indies or jobseeker

**Comment by utilForever** [comment]
Thanks for your suggestion. However, I don't know what to learn to become a game producer/marketer.
Anyone who can help is welcome.
