### ISSUE TITLE
godot game engine is missing

### ISSUE THREAD

**Issue by babak-karimi-asl** [utilForever/game-developer-roadmap#15]
please add [godot game engine](https://godotengine.org/) in game engines graph . it is a really powerful game engine .

**Comment by utilForever** [comment]
@babak-karimi-asl Hi, thanks for your suggestion. I'll consider it. :wave:

**Comment by Xrayez** [comment]
> I'll consider it.

From disclaimer:

> The purpose of this roadmap is to give you an idea about the landscape and to guide you if you are confused about what to learn next and not to encourage you to pick what is hip and trendy.

If the hype is concern, the engine is quite newbie-friendly so I don't see a reason why it can't be added. I'm glad I picked Godot two years ago myself.
