### ISSUE TITLE
Game Tester (QA) path missing?

### ISSUE THREAD

**Issue by ijohnnyjohnny** [utilForever/game-developer-roadmap#16]
Hi! Great job done! 🥇 

In my opinion you could include Game Tester path in your roadmap since this role is an important part of gamedev industry. There wouldn't be so much to do in fact: you can reuse parts of Client Roadmap (like Game Mathematics, Game Physics, Game Engines) and add what's missing (more scripting languages, UX, testing methodology, etc.).

Just a suggestion! 👍 I can help if you decide that my proposition is worth doing.

**Comment by utilForever** [comment]
@ijohnnyjohnny Hi, thanks for your suggestion. However, I can't make game QA roadmap because I don't know everything what QA does. Could you help for me? :sos:

**Comment by ijohnnyjohnny** [comment]
@utilForever Sure, it'll be a pleasure. Just let me gather resources so I can show you anything useful for that new path. Then we can think what's next.
