### ISSUE TITLE
Submit to roadmap.sh

### ISSUE THREAD

**Issue by maniflames** [utilForever/game-developer-roadmap#23]
Right now the creator of the repository that contains the web development roadmap has created [roadmap.sh](https://roadmap.sh/roadmaps). The goal seems to be to collect roadmaps off all sort of developers and not just web developers (at least that is how I've interpreted [his comment on an issue in the repo](https://github.com/kamranahmedse/developer-roadmap/issues/544#issuecomment-570762433)). 

I'd love to see game development up there since this roadmap already matches the style of the others I think it's a perfect candidate 😄 

I don't mind helping out by [filing a submission](https://github.com/kamranahmedse/roadmap.sh/blob/master/contributing/roadmap.md), I'd just like to know your thoughts on doing this in the first place.

**Comment by utilForever** [comment]
Thanks for your suggestion. I'll submit it when I change 2020 ver.
