### ISSUE TITLE
Why is HTML5 listed as a programming language?

### ISSUE THREAD

**Issue by VeryEvilTomato** [utilForever/game-developer-roadmap#25]
I understand HTML5 has certain aspects of declarative programming, but I think it's not good to the whole equation due to it being turing incomplete, why not swap it with an actual webgame programming language such as JavaScript?

**Comment by flamendless** [comment]
Yeah HTML should not be listed because basically JS powers most web game frameworks

**Comment by utilForever** [comment]
I'll replace HTML5 with JavaScript when I change 2020 ver. Thanks.

**Comment by VeryEvilTomato** [comment]
Thank you, sorry for not adding the label, didn't notice that!
