### ISSUE TITLE
About the renewal

### ISSUE THREAD

**Issue by utilForever** [utilForever/game-developer-roadmap#26]
Hello, everyone!
First, I'm so sorry because of no updates.
I'm very busy now by implementing some open source projects such as [RosettaStone](https://github.com/utilForever/RosettaStone) and [CubbyFlow](https://github.com/utilForever/CubbyFlow).
However, I'm preparing cpp-developer-roadmap and renewal of game-developer-roadmap by year´s end.
So, please wait. 🙏

**Comment by amdcat0419** [comment]
Oh!! I am very anticipating the rewel. What will be enhanced in the renewl?
