### ISSUE TITLE
Ultralight and HTML5/JS

### ISSUE THREAD

**Issue by AverageComet250** [utilForever/game-developer-roadmap#29]
I noticed an issue (#25) saying to remove html, but I think it would be better if it says html/JS instead. Another thing would be added ultralight to game engines, however it requires manual physics calculations, and uses HTML, JS and C++ together. It's pretty much just a UI library, but with either an open source physics engine or a custom one it can be quite useful. It's also going for adding a UI to a game server.

**Comment by utilForever** [comment]
Thanks for suggestion. That's right! I strongly agree. I'll consider it to next roadmap.
