### ISSUE TITLE
"Start building" implies you should learn everything first

### ISSUE THREAD

**Issue by idbrii** [utilForever/game-developer-roadmap#31]
The roadmaps end with a "Start building" node which makes them seem even more intimidating -- like you should learn all that stuff before you build anything. The webdev ones end with "keep learning" which is much more encouraging.

If you wanted something different maybe "explore new areas" or "push the boundaries"?

**Comment by utilForever** [comment]
Thanks for suggestion. I'll consider it for next roadmap. 😄
