### ISSUE TITLE
Incorrect intro

### ISSUE THREAD

**Issue by AverageComet250** [utilForever/game-developer-roadmap#32]
The intro says either client or server, when you should in reality know both. Saying developer or tester would make more sense, and splitting developer into client and server would also make more sense.

**Comment by utilForever** [comment]
I don't agree. I don't know why you want to say developer or tester.

**Comment by AverageComet250** [comment]
To me the main issue is client **OR** server, as a good developer should try and know the basics of server as well as client.

**Comment by utilForever** [comment]
I understand and agree your opinion. However, people express it like that because they have the freedom to choose. 😄
