### ISSUE TITLE
The Future of game-developer-roadmap

### ISSUE THREAD

**Issue by utilForever** [utilForever/game-developer-roadmap#33]
Hello, I'm Chris. Long time no see!
First of all, thank you for your interest in the repository. And I'm sorry that I haven't uploaded any content for a long time. Currently,  I'm working on several open source projects such as [RosettaStone](https://github.com/utilForever/RosettaStone) and [CubbyFlow](https://github.com/CubbyFlow/CubbyFlow). Also, I'm very busy because the technology stack has changed recently as I changed jobs. The reason why I am writing like this is to talk about the future.

## Roadmap

I'll start to make the roadmap step by step. The order in which I will work in the future is as follows.

- [x] Client Programmer
  - [x] The Basics
  - [x] Game Mathematics
  - [x] Game Physics
  - [x] Data Structures
  - [x] Algorithms
  - [x] Game Engines
  - [x] Programming Languages
  - [x] Computer Theory
  - [x] Computer Graphics (Rendering)
  - [x] Artificial Intelligence
- [x] Server Programmer (TBD)

If there is no special reason, I'll update the roadmap every week. And I'll write a progress report and share it with you. I plan to finish this work by the fourth quarter of this year. Of course, I inform you that it can be postponed depending on the situation. However, I'll do our best to proceed as planned.

Please give me a lot of support so that I can complete this roadmap safely. Thank you.

**Comment by K-Hacer** [comment]
Hi Chrish, I'm beginner in game dev and I don't know where to start:(  Can you help me?

**Comment by breakingtherabbit** [comment]
@K-Hacer a good option use this roadmap version in https://roadmap.sh/game-developer

**Comment by utilForever** [comment]
I'm preparing update for 2026. Stay tuned! 🎃
