### ISSUE TITLE
Now give us a step by step one

### ISSUE THREAD

**Issue by kamranahmedse** [utilForever/game-developer-roadmap#6]
Hey, nice work on the roadmap. I have been working on making the roadmaps a little bit more structured, to let the people approach it in a step by step manner. Have a look at it and see if you can make the similar :)

https://github.com/kamranahmedse/developer-roadmap#-frontend-roadmap

**Comment by utilForever** [comment]
Thanks. Your work is so great! I'll work it soon. :+1:
